# Generated by Django 4.2.4 on 2023-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreCard', '0002_alter_bar_bar_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='bar_score',
            field=models.IntegerField(default=0),
        ),
    ]
