# Generated by Django 4.2.4 on 2023-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreCard', '0003_total_bar_bar_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
