# Generated by Django 4.2.4 on 2023-08-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreCard', '0005_golfer_score_delete_bar_delete_total_golfer_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfer',
            name='score',
        ),
        migrations.AddField(
            model_name='golfer',
            name='brat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='brothers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='clancys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='depot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='do_dodge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='dooleys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='gi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='mouse_trap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='pickle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='pio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='reboot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='shenanns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='sports_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='wigwam',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
