# Generated by Django 4.2.4 on 2023-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreCard', '0006_remove_golfer_score_golfer_brat_golfer_brothers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarPar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_dodge', models.IntegerField(default=0)),
                ('wigwam', models.IntegerField(default=0)),
                ('depot', models.IntegerField(default=0)),
                ('sports_page', models.IntegerField(default=0)),
                ('reboot', models.IntegerField(default=0)),
                ('mouse_trap', models.IntegerField(default=0)),
                ('clancys', models.IntegerField(default=0)),
                ('dooleys', models.IntegerField(default=0)),
                ('gi', models.IntegerField(default=0)),
                ('brothers', models.IntegerField(default=0)),
                ('pio', models.IntegerField(default=0)),
                ('pickle', models.IntegerField(default=0)),
                ('shenanns', models.IntegerField(default=0)),
                ('brat', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
