# Generated by Django 4.2.4 on 2023-08-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreCard', '0007_barpar'),
    ]

    operations = [
        migrations.AddField(
            model_name='barpar',
            name='elbow_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfer',
            name='elbow_room',
            field=models.IntegerField(default=0),
        ),
    ]
